# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Phillip R. Polefrone"
description: > # this means to ignore newlines until "email:"
   

email: pp2454@columbia.edu
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: ""
imageattr: "image by Bob Eggleton, from the cover of Robert A. Heinlein's 'Farmer in the Sky' (Baen, 2008)"
name: 'Phillip R. Polefrone'
author: 'Phillip R. Polefrone'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://philliprpolefrone.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@polefrone'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-56282998-4

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/polefrone
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/prpole
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
